version: '4.0'

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset analysis/dm_reg_dataset_lola.py
      --test-data-file analysis/test_dm_reg_dataset_lola.py
      --output output/dm_reg_dataset_lola.csv
    outputs:
      highly_sensitive:
        dataset: output/dm_reg_dataset_lola.csv
  
  generate_dm017_measures:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition_dm017.py
      --output output/dm/dm017_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/dm/dm017_measures.csv