version: '4.0'

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset analysis/dm_reg_dataset_lola.py
      --output output/dm_reg_dataset_lola.csv
    outputs:
      highly_sensitive:
        dataset: output/dm_reg_dataset_lola.csv