from ehrql import codelist_from_csv
dm_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dm_cod.csv", column="code")
dmres_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dmres_cod.csv", column="code")
dsep_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dsep_cod.csv", column="code")
dmpcapu_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dmpcapu_cod.csv", column="code")
dmpcadec_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dmpcadec_cod.csv", column = "code")
dseppu_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dseppu_cod.csv", column="code")
dsepdec_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dsepdec_cod.csv", column="code")
dsepsu_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dsepsu_cod.csv", column="code")
dminvite_cod = codelist_from_csv("codelists/nhsd-primary-care-domain-refsets-dminvite_cod.csv", column="code")